In [1]:
import pandas as pd
import cryptpandas as crp
from IPython.display import clear_output

In [2]:
password = input('Password? ')
clear_output()

In [3]:
filename = 'SMMIS data (1988-2000).crypt'

In [4]:
df = crp.read_encrypted(filename, password=password)
df.set_index('recordno', inplace=True)
df.head()

,hospital,hospname,year,ed91,crstairs,crsquint,mhospnum,birthord,birthmth,recstat,...,mdest,bornat,infnhsno,timdish,ethniccd,ethnicp,infethcd,infethp,eclampsia,season
recordno,,,,,,,,,,,,,,,,,,,,,
1.0,1.0,Edgware General Hospital,1988.0,02ARFE06,3.0,5.0,121501,1.0,10.0,5,...,None,NaN,None,NaN,None,None,None,None,None,Autumn
2.0,1.0,Edgware General Hospital,1988.0,None,NaN,NaN,222222,1.0,1.0,6,...,None,NaN,None,NaN,None,None,None,None,None,Winter
3.0,1.0,Edgware General Hospital,1988.0,02ARFW11,-1.0,3.0,422294,1.0,8.0,G,...,T,NaN,None,NaN,None,None,None,None,None,Summer
4.0,1.0,Edgware General Hospital,1988.0,02ARFA06,-1.0,2.0,B023774,1.0,6.0,H,...,U,NaN,None,NaN,None,None,None,None,None,Summer
5.0,1.0,Edgware General Hospital,1988.0,None,NaN,NaN,B114268,1.0,12.0,G,...,U,NaN,None,NaN,None,None,None,None,None,Winter